
CREATE USER SMER_USER IDENTIFIED BY 1234
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO SMER_USER;
GRANT CREATE SESSION TO SMER_USER;
GRANT CREATE TABLE TO SMER_USER;
GRANT CREATE SEQUENCE TO SMER_USER;
GRANT CREATE TRIGGER TO SMER_USER;
GRANT CREATE VIEW TO SMER_USER;
GRANT CREATE PROCEDURE TO SMER_USER;
GRANT UNLIMITED TABLESPACE TO SMER_USER;

SELECT USERNAME, ACCOUNT_STATUS, DEFAULT_TABLESPACE
FROM DBA_USERS
WHERE USERNAME = 'SMER_USER';
