-- ============================================================
-- SMER — Triggers de autoincremento para todas las tablas
-- Ejecutar en SQL Developer como C##SMER
-- ============================================================

CREATE OR REPLACE TRIGGER trg_instituciones_id
BEFORE INSERT ON INSTITUCIONES
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := SEQ_INSTITUCIONES.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_usuarios_id
BEFORE INSERT ON USUARIOS
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := SEQ_USUARIOS.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_estudiantes_id
BEFORE INSERT ON ESTUDIANTES
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := SEQ_ESTUDIANTES.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_periodos_id
BEFORE INSERT ON PERIODOS
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := SEQ_PERIODOS.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_entrevistas_id
BEFORE INSERT ON ENTREVISTAS
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := SEQ_ENTREVISTAS.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_indicadores_id
BEFORE INSERT ON INDICADORES_ENTREVISTA
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := SEQ_INDICADORES.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_config_riesgo_id
BEFORE INSERT ON CONFIGURACION_RIESGO
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := SEQ_CONFIG_RIESGO.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_derivaciones_id
BEFORE INSERT ON DERIVACIONES
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := SEQ_DERIVACIONES.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_alertas_id
BEFORE INSERT ON ALERTAS
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := SEQ_ALERTAS.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_documentos_id
BEFORE INSERT ON DOCUMENTOS_ADJUNTOS
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := SEQ_DOCUMENTOS.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_auditoria_id
BEFORE INSERT ON AUDITORIA
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := SEQ_AUDITORIA.NEXTVAL;
END;
/

COMMIT;

-- Verificar triggers creados
SELECT trigger_name, table_name, status
FROM user_triggers
WHERE trigger_name LIKE 'TRG_%_ID'
ORDER BY table_name;
